### ISSUE TITLE
[2.0.0] 위젯 작업을 위한 appGroup 세팅

### ISSUE THREAD

**Issue by lgvv** [ku-ring/app-ios-v2#109]
## 개요
 - 실험실에 위젯을 만들어보려고 하는데, v2에서 appGroup을 사용할 수 있도록 세팅을 하는건 어떨까요?

##

애플 디벨롭 사이트에서 appGroup 추가하기
 - 근데 이게 제가 접근이 안되는 것으로 보여서 권한 있으신 분이 확인해주시면 좋을 것 같습니다.

### 기대효과 (선택사항)
 - `성수`님도 소소하게 참여하실 수 있을 것으로 보입니다.
 @sunshiningsoo 

## 대안 (선택사항)
 - `위젯`과 동떨어져서 개발 가능.

**Comment by x-0o0** [comment]
@lgvv 
com.kuring.service 에 앱그룹 추가하였습니다

<img width="749" alt="스크린샷 2024-01-27 오전 12 16 21" src="https://github.com/ku-ring/ios-app/assets/53814741/92d812ce-c98a-4575-a479-dec20e96091f">

<img width="1066" alt="스크린샷 2024-01-27 오전 12 05 40" src="https://github.com/ku-ring/ios-app/assets/53814741/78a44160-228b-4769-b513-117fd088f06b">
