### ISSUE TITLE
[2.0.0] 온보딩

### ISSUE THREAD

**Issue by x-0o0** [ku-ring/app-ios-v2#110]
## 개요
처음 쿠링을 사용하는 유저를 위한 온보딩 페이지가 필요합니다.

예) 
Swift Package Based Modularization(이하 PBM) 으로 전환하기
전환하려는 이유는, Tuist 로 모듈화 하면서 학습해야하는 것과 에러를 부딪힐때마다 공식문서 살펴보고 구글링 하고 자료를 찾아보고 하는 것이 기초 작업에 너무 큰 리소스를 사용하고 있다고 생각이 들었음.

## 온보딩

~쇼케이스 (또는 하이라이트) 형태의 온보딩을 통해 처음 쿠링을 사용하는 유저들이 쿠링의 주요 기능을 쉽게 파악할 수 있도록 해야 합니다.~

온보딩을 별도의 라이브러리로 분리
`Onboarding` ---has dependencies---> `SubscriptionFeatures`, `SubscriptionUI`

#### 앱에서의 사용
 ```swift
 struct ContentView: View {
    var body: some View {
        NavigationView {
            // ...
        }
        .onboadingCover()
    }
 }
 ```
 
#### 버전별 온보딩 관리 - 별도의 패키지로 분리되면 고려
 ```swift
 ContentView()
    .environment(
        \.onboarding,
        OnboardingValues(
            history: self.onboardingHistory
        )
 ```

 ```swift
 var onboardingHistory: OnboardingHistory {
    Onboarding(
        version: "2.0.0",
        // ...
    )
 
     Onboarding(
         version: "2.1.0",
         // ...
     )
     
     Onboarding(
         version: "2.2.0",
         // ...
     )
 }
 ```

#### 온보딩 화면 정보 구성
 ```swift
 let onboarding = Onboarding(
    version: "2.0.0",
    title: "건국대 공지\n쿠링이 알려줄게!",
    features: [
        Onboarding.Feature(
            image: .init(image: ""),
            title: "빠른 공지 확인",
            subtitle: "학교 홈페이지에 들어갈 필요없이 메인페이지에서 공지사항을 바로 확인해 보세요."
        )
    ],
    primaryAction: Onboarding.PrimaryAction(
        title: "다음",
        backgroundColor: .accentColor,
        foregroundColor: .white,
        hapticFeedback: .notification(.success),
        onDismiss: { 
            // ...
        }
    ),
    secondaryAction: Onboarding.SecondaryAction(
        title: "설명 괜찮아요. 바로 시작할게요!",
        foregroundColor: .secondary,
        hapticFeedback: .selection,
        onDismiss: {
            // ...
        }
    )
 )
 ```

#### 1안
|  검색 | 구독 | 학과 추가 | 공지보관함 | 
| --- | --- | --- | --- |
|  ![메인화면_학과_추가된 학과가 없을 경우](https://github.com/ku-ring/ios-app/assets/53814741/34c7da97-6acd-421b-8207-cc9c83c65a9e) | ![메인화면_학과_추가된 학과가 없을 경우-2](https://github.com/ku-ring/ios-app/assets/53814741/4b089dee-fc82-4597-8712-f28fad143d60) |  ![메인화면_학과_추가된 학과가 없을 경우-3](https://github.com/ku-ring/ios-app/assets/53814741/817ef513-5d05-4102-a617-2e5179b2aebb) | ![메인화면_학과_추가된 학과가 없을 경우-4](https://github.com/ku-ring/ios-app/assets/53814741/bf34f6dd-c8e8-4c75-866c-f56f7745dc98) |

#### 2안 (확정)

<img width="569" alt="스크린샷 2024-03-10 오전 2 37 02" src="https://github.com/ku-ring/ios-app/assets/53814741/f335d29e-1b71-436a-a91e-bd5db514c28f">
<img width="965" alt="스크린샷 2024-03-10 오전 2 37 14" src="https://github.com/ku-ring/ios-app/assets/53814741/3d80591e-dfbe-4e99-bd97-1282a0fa2d29">

**Comment by lgvv** [comment]
@x-0o0 

이건 전체 화면을 이미지 영역으로 잡아 Pager형태로 처리하는건 어떨까요?
 - 공수가 가장 적어 보입니다!

**Comment by x-0o0** [comment]
@lgvv 

맞아요 건우님 의견도 너무 좋습니다! 공수가 가장 적을것 같아요!

그전에 한번 실험해보고 싶은게 있어서 실험 한번 해보려구 합니다! (그전에 건우님이 작업하셔도 좋구요☺️)

저런 거를 Spotlight, Showcase, highlight 다양하게 부르더라구요. 그래서 관련된거 찾아보고 있는데

- https://www.youtube.com/watch?v=I9v-zqrE8gI
- https://kavsoft.dev/swiftui_4.0_spot_light_jul

이렇게 참고해보고 있습니다!

```swift
Button("버튼") {
}
.showcase(order: 0, message: "어떤 역할을 하는 버튼입니다")
```
이런식으로 view modifier 형식으로 하면 새로운 기능 추가때마다 온보딩에 추가하기 좋을거 같아요!

**Comment by x-0o0** [comment]
### `PreferenceKey`
```swift
struct BoundsPreferenceKey: PreferenceKey {
    static var defaultValue: Anchor<CGRect>? = nil

    static func reduce(value: inout Value, nextValue: () -> Value) {
        // merge here
    }
}
```
### `. anchorPreference`
```swift
// ExampleView
Text("Hello World !!!")
    .anchorPreference(
        key: BoundsPreferenceKey.self,
        value: .bounds
    ) { $0 }
}
```
### `.overlayPreferenceValue`
```swift
RootView {
    // ExampleView goes here
}
.overlayPreferenceValue(BoundsPreferenceKey.self) { preferences in
    GeometryReader { proxy in
        // shows SpotlightView if `preferences` is not empty
    }
}
```

<img src="https://github.com/ku-ring/ios-app/assets/53814741/8a0af0fb-537d-4cdc-beb5-d32f7d078cf1" alt="img" width="200"/>

### 이슈
tab bar 랑 navigation bar에서는 안되는 것 같음

**Comment by lgvv** [comment]
쇼케이스..! 이건 처음 본 개념인데 신기하네요!!! 저도 공부해보겠습니다!

**Comment by x-0o0** [comment]
Public API References
- https://github.com/SvenTiigi/WhatsNewKit

**Comment by x-0o0** [comment]
> **디자이너 피드백**
>
> 디자인 관점에서 두번째 온보딩 페이지 디자인이 좋을것같다고 생각하긴합니다! 
> 
> 이유를 간단히 설명드리자면, 위의 오픈소스처럼 한 페이지에 기능들에 대한 소개가 다 들어가면 아무래도 텍스트의 양이 많아지기 때문에 사용자 입장에선 읽고 싶지 않을 것 같았어요! 그래서 두번째 온보딩 디쟈인처럼 한 페이지에 하나의 기능만 소개해서 아이콘의 크기를 좀 키우고 텍스트의 양을 줄이면, 온보딩 페이지들을 빠르게 넘어가더라도 기능들에 대한 정보가 눈에는 좀 더 잘 들어오지않을까 생각했습니다
> 
> 근데 개발 시간 이슈때문이라면 오픈소스 사용도 괜찮을것같아요. 온보딩파트보다 사실 실제 앱 내의 다른 기능들이 작동하는게 더 중요하니까여 개발 시간이 빠듯하다면 온보딩은 오픈소스 사용으로 시간단축하는게 나을것같다는 생각이 들어요!

> **디자이너 피드백**
>
> ios 부분에 디자인되어있는데 일러스트 아이콘으로 넣을지 스크린샷으로 넣을지 아직 정하지 못한상태입니다

## 온보딩 구독
- 전공학과만 구독하도록

**Comment by x-0o0** [comment]
온보딩은 디자인 진행중이라 일시중단

**Comment by x-0o0** [comment]
Lottie: [success.json](https://github.com/ku-ring/ios-app/files/14349143/success.json)
