### ISSUE TITLE
[이슈] 피드백 글자수 max 제한 미적용

### ISSUE THREAD

**Issue by x-0o0** [ku-ring/app-ios-v2#114]
## 이슈 설명
256 자가 넘어가면 store.isSendable 이 false가 되어 guideline 색상 변경이 발생해야함

## 재현방법
1. 피드백 보내기로 이동
2. 256 자 이상 작성하기
3. 버튼 활상화 여부, 가이드 문구 확인

## 기대결과
디자인에 맞춰서 256 자 초과시 전송 못 하도록 처리해야 합니다

## 스크린샷
![image](https://github.com/ku-ring/ios-app/assets/53814741/f4c054bf-e417-46c2-a180-87b78e6b08a3)

## 버전 정보

| 플랫폼 | 버전 |
| --- | --- |
| 쿠링 앱 | 2.0.0 |
| iOS | 17.2.1 |
| Xcode | - |

**Comment by lgvv** [comment]
이거 제가 보겠습니다 @x-0o0
