### ISSUE TITLE
[2.0.0] 보관된 공지 스포트라이트 검색 기능

### ISSUE THREAD

**Issue by x-0o0** [ku-ring/app-ios-v2#128]
## 개요
1.4.3 버전부터 스포트라이트 기능을 제공하고 있기 때문에 2.0 에서도 동일하게 기능을 제공해줘야 합니다.

## 공지보관함 스포트라이트 검색 기능

기능에 대한 작업 방법이나 구체적인 기능 설명, 예시 코드 등

### 디자인
스크린샷이나 다이어그램

**Comment by lgvv** [comment]
@x-0o0 

`feature`로 분리해서 작업하고자 하는데, 작업 전에 어떤 방향성으로 해야할 지 고민이여서 코멘트 남깁니다!

제가 생각하는 방향은 `AppDelegateFeature`에서 모아서 처리하는건 어떨까 싶습니다.
해당 Feature에서 우선순위 큐를 도입하여, 노티피케이션, 화면의 생성 등을 통합 관리하고자 합니다.

제안하는 이유로는 현재 저희 앱이 외부에서 노티피케이션을 클릭시 1초 딜레이를 두고 있는데, 우선순위 큐를 도입하여 해당 이벤트를 우선순위에 맞게 안정적으로 관리할 수 있다고 생각합니다. 

### 우선순위를 정해야 하는 목록
 - 앱 시작시, 최소지원 버전 체크 api
 - 스포트라이트 기능
 - 위젯 리로드 기능
 - FCM
 - 로컬 노티피케이션
 - 화면 구성
 - 서버에 fcm 등록

**Comment by x-0o0** [comment]
> @x-0o0 
> 
> 
> 
> `feature`로 분리해서 작업하고자 하는데, 작업 전에 어떤 방향성으로 해야할 지 고민이여서 코멘트 남깁니다!
> 
> 
> 
> 제가 생각하는 방향은 `AppDelegateFeature`에서 모아서 처리하는건 어떨까 싶습니다.
> 
> 해당 Feature에서 우선순위 큐를 도입하여, 노티피케이션, 화면의 생성 등을 통합 관리하고자 합니다.
> 
> 
> 
> 제안하는 이유로는 현재 저희 앱이 외부에서 노티피케이션을 클릭시 1초 딜레이를 두고 있는데, 우선순위 큐를 도입하여 해당 이벤트를 우선순위에 맞게 안정적으로 관리할 수 있다고 생각합니다. 
> 
> 
> 
> ### 우선순위를 정해야 하는 목록
> 
>  - 앱 시작시, 최소지원 버전 체크 api
> 
>  - 스포트라이트 기능
> 
>  - 위젯 리로드 기능
> 
>  - FCM
> 
>  - 로컬 노티피케이션
> 
>  - 화면 구성
> 
>  - 서버에 fcm 등록 

1. 화면 구성이 UI 건드는게 아닌거죠?
2. 앱 시작시 최소버전 체크는 CommonUI 모듈에 이미 들어가 있어서 KuringApp 에서 `.versionUpdateAlert()` view modifier 추가해주면 됩니다. (PR https://github.com/ku-ring/ios-app/pull/125)


건우님 의견이 매우 좋긴 한데, AppDelegateFeatures 하나로 다 들어가기엔 목적이 서로 달라 애매해 보여요. 그리고 작업 기간이 오래 걸려 발목 잡힐까 걱정되구요.
우선은 Spotlight 에 대한 모듈, Notifications 에 대한 모듈은 서로 분리 되어서 작업되면 좋을것 같고 참고로 Notifications 에 대한 이슈도 생성되어 있습니다.

**Comment by lgvv** [comment]
> > @x-0o0
> > `feature`로 분리해서 작업하고자 하는데, 작업 전에 어떤 방향성으로 해야할 지 고민이여서 코멘트 남깁니다!
> > 제가 생각하는 방향은 `AppDelegateFeature`에서 모아서 처리하는건 어떨까 싶습니다.
> > 해당 Feature에서 우선순위 큐를 도입하여, 노티피케이션, 화면의 생성 등을 통합 관리하고자 합니다.
> > 제안하는 이유로는 현재 저희 앱이 외부에서 노티피케이션을 클릭시 1초 딜레이를 두고 있는데, 우선순위 큐를 도입하여 해당 이벤트를 우선순위에 맞게 안정적으로 관리할 수 있다고 생각합니다.
> > ### 우선순위를 정해야 하는 목록
> > 
> > * 앱 시작시, 최소지원 버전 체크 api
> > * 스포트라이트 기능
> > * 위젯 리로드 기능
> > * FCM
> > * 로컬 노티피케이션
> > * 화면 구성
> > * 서버에 fcm 등록
> 
> 1. 화면 구성이 UI 건드는게 아닌거죠?
> 2. 앱 시작시 최소버전 체크는 CommonUI 모듈에 이미 들어가 있어서 KuringApp 에서 `.versionUpdateAlert()` view modifier 추가해주면 됩니다. (PR [[2.0.0] 버전 업데이트 알림 기능 추가 #125](https://github.com/ku-ring/ios-app/pull/125))
> 
> 건우님 의견이 매우 좋긴 한데, AppDelegateFeatures 하나로 다 들어가기엔 목적이 서로 달라 애매해 보여요. 그리고 작업 기간이 오래 걸려 발목 잡힐까 걱정되구요. 우선은 Spotlight 에 대한 모듈, Notifications 에 대한 모듈은 서로 분리 되어서 작업되면 좋을것 같고 참고로 Notifications 에 대한 이슈도 생성되어 있습니다.

해당 부분 코드로 구현하다가 막혀서 잠시 멈췄습니다!

bookamrk dependency에서 add시 스포트라이트 등록하는 방법도 있을 것 같기도 하고,
feature로 구현하면 Scope에서 bookmark가 처리되기 전에 이벤트가 처리되어 버릴거 같고,

어떤 방법으로 하면 좋을지가 고민입니다.

**Comment by x-0o0** [comment]
> bookamrk dependency에서 add시 스포트라이트 등록하는 방법도 있을 것 같기도 하고,

@lgvv 건우님 의견 좋습니다~! 제가 드리는 제안은 아래 두가지 입니다.

### 방법1 Spotlight 디펜던시 생성해서 NoticeFeatures 에서 사용하기
장점: 스포트라이트 기능이 필요한 Feature 가 어딘지 의존성을 명확히 알 수 있음. Bookmark 와 독립적이어서 `Caches` 모듈을 의존성으로 갖는 Features 들이 불필요하게 스포트라이트를 의존하는 일이 없고 추후 스포트라이트 지원 범위 확장시 좋을 수 있음.
1. `Spotlight` 디펜던시 생성
```swift
import Models

struct Spotlight: DependencyKey {
    static let liveValue = Spotlight(
        update: { notice in
            let attributeSet = CSSearchableItemAttributeSet(contentType: .text)
            // ...
        }
    )
}
```

2. NoticeFeatures 에 `Spotlight` 를 의존성으로 추가
```swift
target(
    "BookmarkFeatures",
    dependencies: "Caches", "Spotlight"
)
```
3. NoticeFeatures 에서 북마크시 스포트라이트 업데이트
```swift
import Spotlight

@Dependency(\.spotlight) var spotlight
case let .updateBookmarks(notice, isBookmarked):
    do {
        if isBookmarked {
            try bookmarks.add(notice)
            spotlight.update(notice)
        }
    }
```

### 방법2. 스포트라이트에 대한 클래스 하나 생성(스포트라이트 디펜던시도 OK)해서 Bookmark 디펜던시 내에서 사용하기
장점: 북마크의 업데이트 하는 코드 한군데에서만 스포트라이트 인터페이스를 호출하면 됨 (유지보수 용이). `Caches` 모듈에 포함되기 때문에 해당 모듈을 쓰는 모든 Features 는 스포트라이트 기능이 필요없어도 해당 코드에 의존성을 갖게 됨.
```swift
// 싱글톤 매니저 클래스 방식
class Spotlight {
    static let client = Spotlight()
    func update(with notice: Notice) { ... }
}

extension Bookmarks {
    public static let `default` = Bookmarks(
        add: { notice in
            // ...
            Spotlight.client.update(with: notice)
```
또는
```swift
// TCA 디펜던시 방식
struct Spotlight: DependencyKey {
    static let liveValue = Spotlight(
        update: { notice in
            let attributeSet = CSSearchableItemAttributeSet(contentType: .text)
            // ...
        }
    )
}

extension Bookmarks {
    public static let `default` = Bookmarks(
        add: { notice in
            // ...
            @Dependency(\.spotlight) var spotlight
            spotlight.update(notice)
```
