### ISSUE TITLE
[QA 이슈 리포트] **Discussions 로 이동합니다**

### ISSUE THREAD

**Issue by x-0o0** [ku-ring/app-ios-v2#189]
(1) 이슈 내용, (2) 재현 방법, (3) 기대 결과에 대한 정보를 공유해주세요.

스크린샷까지 있으면 빠르게 파악되는데에 도움이 됩니다.

**Comment by x-0o0** [comment]
- 앱 처음 설치할 때만 네트워크 에러가 발생했다는 알림이 뜨는 현상
- 기대 결과: 에러가 발생하면 안됨

**Comment by x-0o0** [comment]
![KakaoTalk_Photo_2024-03-28-22-55-03](https://github.com/ku-ring/ios-app/assets/53814741/59cb3f60-2d65-44ea-b00e-9ff6d44fccbe)

1. 네비게이션바 타이틀 수정 필요
2. 검색 필터링 안됨

**Comment by x-0o0** [comment]
![KakaoTalk_Photo_2024-03-28-22-55-13](https://github.com/ku-ring/ios-app/assets/53814741/5eaa8975-ccc3-468d-88b7-a0d81b600cab)

- 공유하기 (ActivitySheet) 가 공지 웹뷰에서 홈화면으로 나갔을 때 다시 뜨는 현상
- 다시 뜨면 안됨

**Comment by x-0o0** [comment]
- v1 에 있던 터치 피드백이 v2에 없음

**Comment by x-0o0** [comment]
- 폰트 적용 필요
- 네이게이션바, 탭바 아이콘 변경 필요

https://www.figma.com/file/TNE2bB1Y18gIK74asokOK4?type=design&node-id=2214-11997&mode=dev#713326586

**Comment by x-0o0** [comment]
- 검색시 placeholder 를 아래와 같이 변경해야함
`"공지 제목 또는 교수명을 입력해주세요"`
(https://www.figma.com/file/TNE2bB1Y18gIK74asokOK4?type=design&node-id=273-5635&mode=dev#713600877)

**Comment by lgvv** [comment]
> ![KakaoTalk_Photo_2024-03-28-22-55-03](https://private-user-images.githubusercontent.com/53814741/317752148-59cb3f60-2d65-44ea-b00e-9ff6d44fccbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDA4NzUsIm5iZiI6MTcxMTY0MDU3NSwicGF0aCI6Ii81MzgxNDc0MS8zMTc3NTIxNDgtNTljYjNmNjAtMmQ2NS00NGVhLWIwMGUtOWZmNmQ0NGZjY2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE1NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNmM0NjUwNzRkMzU2YzMyZTgwZGM0ZmM3YzkxMzQxYzRlMjUwYjUwYjk4OWM2NzJhNTQwM2MwMDBmMzA1NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_86SryGu-gTde9Zdm9T_Q_VDh-QwaxgRC7aX_WVUgo)
> 
> 1. 네비게이션바 타이틀 수정 필요
> 2. 검색 필터링 안됨

원인) 기존에 검색 로직이 구현되어 있지 않음.
해결) v1에 적용된 학과 검색 로직을 적용함.

**Comment by lgvv** [comment]
> ![KakaoTalk_Photo_2024-03-28-22-55-13](https://private-user-images.githubusercontent.com/53814741/317752547-5eaa8975-ccc3-468d-88b7-a0d81b600cab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDA5ODksIm5iZiI6MTcxMTY0MDY4OSwicGF0aCI6Ii81MzgxNDc0MS8zMTc3NTI1NDctNWVhYTg5NzUtY2NjMy00NjhkLTg4YjctYTBkODFiNjAwY2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE1NDQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNDExYmU3Mzg3MTkyNjE1YjBhNTllMTliNDA4ODcxMDNjYzczODYyMDQxNDA1NWZkODc2ZjYyNGY4MDA4ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RCuM1iyUEUQwj1f_Ab7TQ_ekoC6M_q6IIkjh_S5eDHo)
> 
> * 공유하기 (ActivitySheet) 가 공지 웹뷰에서 홈화면으로 나갔을 때 다시 뜨는 현상
> * 다시 뜨면 안됨

해결) ShareLink로 교체하면서 해결

**Comment by lgvv** [comment]
> * 검색시 placeholder 를 아래와 같이 변경해야함
>   `"공지 제목 또는 교수명을 입력해주세요"`
>   (https://www.figma.com/file/TNE2bB1Y18gIK74asokOK4?type=design&node-id=273-5635&mode=dev#713600877)

수정) 이것도 제가 빠르게 수정했습니다.

**Comment by x-0o0** [comment]
온보딩에서 바로가기 안누르고 guidance만 확인한 다음 앱 껐다키면 온보딩 안뜨는 현상이 있음.

- 기대결과: 바로가기 클릭하거나 학과선택 완료했을 때만 온보딩 완료된 것으로 처리되어야함

**Comment by x-0o0** [comment]
보관하는 공지가 없을 경우 네비게이션 바의 편집 버튼이 UI 적으로 비활성화 되어야 함

![Simulator Screenshot - iPhone 15 Pro - 2024-03-29 at 03 40 31](https://github.com/ku-ring/ios-app/assets/53814741/e68be1f1-a0e4-4a32-b507-dca46b26a57b)

**Comment by x-0o0** [comment]
대표학과의 경우 "대표" 표시가 필요함

<img width="268" alt="스크린샷 2024-03-29 오전 3 45 05" src="https://github.com/ku-ring/ios-app/assets/53814741/61a543e7-7dee-46ee-8e53-87a1949ea496">

https://www.figma.com/file/TNE2bB1Y18gIK74asokOK4/%F0%9F%90%B8%EC%BF%A0%EB%A7%81-%EB%94%94%EC%9E%90%EC%9D%B8%ED%8C%80%F0%9F%90%B8?type=design&node-id=296-15276&mode=design&t=UZaJYIU20XaOdWFx-4
