### ISSUE TITLE
[2.1.0] 쿠링봇 내부 DB 설계 및 구현

### ISSUE THREAD

**Issue by wonniiii** [ku-ring/app-ios-v2#213]
## 개요
- 한달에 두번의 채팅을 할 수 있어, 대화 데이터는 내부 DB에 저장하기로 했습니다.

## 쿠링봇 내부 DB 설계 및 구현
- 내부 DB로 Core Data, Realm 둘 중에 고민중이긴 하지만, Core Data로 쓸 것 같습니다.
- 이 부분에 대해서 다른 분들 의견있으시면 답변 달아주시면 감사하겠습니다 !

**Comment by x-0o0** [comment]
@wonniiii 

한달 두번 채팅이면 저장 자체는 간단할텐데 겸사겸사 LINE 개발블로그에 있는 메세지 저장에 대한 글인데 한번 읽어보시면 좋을 것 같아요.

https://engineering.linecorp.com/en/blog/new-way-of-managing-chat-storage-in-the-ios-version-of-line

그리고 CoreData 로 하게될 것 같은데 좀 더 나아가 SwiftData 를 써보는 것은 어떠신가요~? 좋은 공부가 되지 않을까 싶어요!

**Comment by wonniiii** [comment]
오홍 SwiftData는 생각 못해봤는데 한번 고려해볼게요 !
