### ISSUE TITLE
[2.1.0] 쿠링봇 UI 구현

### ISSUE THREAD

**Issue by wonniiii** [ku-ring/app-ios-v2#214]
## 개요
- 쿠링봇의 전체 UI를 구현합니다.

## 쿠링봇 UI 구현
- 메인에서 보여지는 FloatingBtn과 질문과 답변 UI를 구현합니다.

### 디자인
<img width="320" alt="스크린샷 2024-07-26 오후 7 30 33" src="https://github.com/user-attachments/assets/bb667e30-2f2d-426d-8bd4-a1055947a583"> <img width="317" alt="스크린샷 2024-07-26 오후 7 31 46" src="https://github.com/user-attachments/assets/649d4653-68c2-417d-a288-4f13c8cb508a">

**Comment by x-0o0** [comment]
@wonniiii 

2022년 학교 축제 대비해서 쿠링챗 기능을 안드로이드와 함께 도입했었습니다.

그 때 커밋들이 남아 있을 거라 쿠링챗 제거를 담당했던 성수님께 한번 커밋기록 찾아달라구 요청해보시면 금방 도와주실 거예요.

당시 SwiftUI 로 채팅 개발하는게 자료가 별로 없어서 성능이 좋진 않아서 참고용으로 보면 좋으실 것 같고, 

지금은 자료도 많으니 더 개선해서 구현이 가능할 것 같아요.

cc. @sunshiningsoo

**Comment by wonniiii** [comment]
넵 둘 다 참고해보겠습니다 !

**Comment by wonniiii** [comment]
넵 둘 다 참고해보겠습니다 !
