### ISSUE TITLE
앱아이콘 변경 가능하게 하기

### ISSUE THREAD

**Issue by x-0o0** [ku-ring/app-ios-v2#22]
## 개요
설정에서 앱아이콘 변경 가능하게 하면 어떨까요.

옛날 앱아이콘도 쓸 수 있고, 쿠링 Lite 아이콘으로도 바꿀 수도 있구요

| kuring.app | kuring.app.sketch | kuring.app.blueprint | kuring.app.classic |
| --- | --- | --- | --- |
| ![kuring app](https://github.com/ku-ring/ios-app/assets/53814741/fc255b66-6bff-4baf-91f0-944a352f73ed) | ![kuring app sketch](https://github.com/ku-ring/ios-app/assets/53814741/1bde9d1f-1c3b-4e19-b322-a0617c113e5e) | ![kuring app blueprint](https://github.com/ku-ring/ios-app/assets/53814741/5fa06331-8dc3-45ca-9256-c429677e2462) | ![kuring app classic](https://github.com/ku-ring/ios-app/assets/53814741/87f986c1-c179-4ab9-9864-8809d759ff2c) |

### 방법

> **애플개발자문서** 
>
> https://developer.apple.com/documentation/xcode/configuring-your-app-icon#Change-the-default-app-icon-set

```swift
UIApplication.shared.setAlternateIconName("APP.ICON")
```

**Comment by x-0o0** [comment]
### 앱아이콘 파일 전달
@sunshiningsoo 

| kuring.app | kuring.app.sketch | kuring.app.blueprint | kuring.app.classic |
| --- | --- | --- | --- |
| ![kuring app](https://github.com/ku-ring/ios-app/assets/53814741/fc255b66-6bff-4baf-91f0-944a352f73ed) | ![kuring app sketch](https://github.com/ku-ring/ios-app/assets/53814741/1bde9d1f-1c3b-4e19-b322-a0617c113e5e) | ![kuring app blueprint](https://github.com/ku-ring/ios-app/assets/53814741/5fa06331-8dc3-45ca-9256-c429677e2462) | ![kuring app classic](https://github.com/ku-ring/ios-app/assets/53814741/87f986c1-c179-4ab9-9864-8809d759ff2c) |

[🐸쿠링앱아이콘🐸.zip](https://github.com/ku-ring/ios-app/files/12727988/default.zip)

**Comment by sunshiningsoo** [comment]
앱 아이콘 파일을 이슈와 같이` kuring.app.png`, `kuring.app.sketch.png` 등의 이미지 파일을 올려두고, `Info.plist` 파일에서 kuring.app을 직접 명명해주어 앱 아이콘을 변경하도록 시도했지만, `Info.plist` 파일에서는 파일명에 `.` 이 들어가 있는 리소스(이미지 파일)을 인식하지 못하는 문제가 생겨 ` . ` 을 언더바 ` _ ` 로 수정하여 반영했습니다.


```
변경 전: kuring.app
변뎡 후: kuring_app
```
