### ISSUE TITLE
[2.0.0] TCA기반의 검색창 구현 

### ISSUE THREAD

**Issue by lgvv** [ku-ring/app-ios-v2#35]
[2.0.0] TCA기반의 검색창 구현

**Comment by x-0o0** [comment]
### TIL
인풋용 뷰의 `onSubmit` 메소드는 메인쓰레드 에서 불림

<img width="1582" alt="스크린샷 2023-10-11 오후 9 03 35" src="https://github.com/ku-ring/ios-app/assets/53814741/3fede349-db34-49e5-af06-183c8f382faf">

**Comment by x-0o0** [comment]
### 논의

`SearchView` 의 프리뷰가 캔버스에 안보여지는 현상(무한로딩) 이 있는데
뷰 내에서 `@ViewBuilder`로 정의하는 방식이 원인인 거 같음

@lgvv @sunshiningsoo
