### ISSUE TITLE
[2.0.0] 더보기 뷰 및 Navigation 연결

### ISSUE THREAD

**Issue by sunshiningsoo** [ku-ring/app-ios-v2#40]
## 내용
앱 이미지 변경을 기능으로 남겨두고, 나머지 설정은 우선 Navigation 연결로 작업할 예정입니다.

### 디자인
<img src="https://github.com/ku-ring/ios-app/assets/72736657/2888a4f9-0a1a-4832-952c-d439a9d8512e" width=300>

## 추후
- 추후 모든 설정 작업 연결 예정입니다.

**Comment by x-0o0** [comment]
## 사전작업

https://github.com/ku-ring/ios-app/pull/41

**Comment by sunshiningsoo** [comment]
#41 pr merge 완료
