### ISSUE TITLE
[버그] SwiftUI TextField issue

### ISSUE THREAD

**Issue by lgvv** [ku-ring/app-ios-v2#43]
## [2.0.0] SwiftUI TextField 블락 이슈
<img width="1305" alt="스크린샷 2023-10-08 오전 12 49 51" src="https://github.com/ku-ring/ios-app/assets/56182112/885706e4-5cbb-4513-a6a7-c7cf9f58837e">

## 재현방법
 - 랜덤하게 발생하나 Development에 걸린 브랜치에서 확인 가능
 - 혹은 아래 TCA 공식 예제에 걸린 부분에서도 확인 가능

## 기대결과
 - 문제를 해결하고자 시도
 - 문제상황) 주로 TextField를 사용할 때 해당 이슈를 만남
   - 가설 1) `@focusState`를 TCA에서 사용할 때 Reducer와 View의 bind를 내가 잘못 연결한게 아닐까?
      - 여러 방법으로 시도했으나 문제 해결 실패
   - 가설 2) main thread와 관련한 워닝도 나타났는데, 비동기 처리에서 어떠한 문제가 있는게 아닐까?
      - 키보드 State를 바꾸는 부분에 `DispatchQueue.main.async { ... }`로 감싸봄.
      - 문제해결 실패
      
 - 그러나 TCA의 공식 예제에서도 동일한 현상 발견
   - 테스트 환경
      - Xcode 15.0 정식출시버전 (앱스토어 다운로드)
      - iOS 17.0
      - iPhone 15 시뮬레이터
   - [해당 문제가 동일하게 나타나는 공식 예제](https://github.com/pointfreeco/swift-composable-architecture/blob/main/Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift)
   - [스택오버플로우 1](https://stackoverflow.com/questions/74286354/ios-16-swiftui-keyboard-safe-area-bug-when-swipe-back)
   - [스택오버플로우 2](https://stackoverflow.com/questions/74019750/ios16-bug-keyboard-breaks-layout-on-sheet-dismissal-swiftui/74622482#74622482)

## 추가 사항
 - 키보드가 블락되는 시간이 발생하지 않거나 혹은 아주 길게 발생하고 있습니다. 이게 길게 발생할 경우 서비스에 큰 영향이 있을 것 같습니다.

/cc @jaesung-0o0 
/cc @sunshiningsoo

**Comment by sunshiningsoo** [comment]
https://github.com/ku-ring/ios-app/pull/34/files#r1349547442 의견 남겨보았습니다!

**Comment by lgvv** [comment]
#### 해결
- TCA에서 바인딩 중첩해서 사용하던 문제
