### ISSUE TITLE
쿠링랩

### ISSUE THREAD

**Issue by x-0o0** [ku-ring/app-ios-v2#5]
## 개요
쿠링 iOS 멤버들이 여러 기술들과 새로운 기능들을 가볍게 테스트해보고 유저들이 사용해볼 수 있는 쿠링랩(KuringLab) 공간이 필요

**Comment by lgvv** [comment]
요 부분도 계속 생각하고 있는데, 어떻게 하는게 베스트일지 수요일에 논의하면 좋을 것 같아요~!~!

**Comment by x-0o0** [comment]
> 요 부분도 계속 생각하고 있는데, 어떻게 하는게 베스트일지 수요일에 논의하면 좋을 것 같아요~!~!

⭐️이번 주 수요일 (10/11) 논의 예정⭐️
