### ISSUE TITLE
Tuist 적용

### ISSUE THREAD

**Issue by x-0o0** [ku-ring/app-ios-v2#6]
## 개요

모듈화를 위해 Tuist 를 적용하여 프로젝트를 생성합니다.

## 디펜던시
| 모듈 이름 | 레포 |
| --- | --- |
| KuringLink | ios-kuringlink |
| KuringMaps | ios-maps |
| Cache | Cache |
| Satellite | the-satellite |
| ComposableArchitecture | swift-composable-architecture |

## 계획

###8월

2일 (수): Tuist 로 프로젝트 환경 구성

**Comment by lgvv** [comment]
해야하는 작업 기록
 - info.plist ( App단에만 적용 완료 )
 - Core/Logger 논의 ( Logger 도입할 구조 완료 )
 - Maps 플러그인, SPM, 내부에서 재구성 논의 ( ? )
 - Enigma xcconfig, 플러그인 등 방법 논의 ( ? )
